### ISSUE TITLE
`sync.pool` failed at terminating

### ISSUE THREAD

**Issue by vanyarock01** [moonlibs/sync#4]
My code (roughly of-course):
```lua
local pool = require'sync'.pool.new(3)

-- some real works

pool:terminate(true)
```
My logs:
<img width="1391" alt="image" src="https://user-images.githubusercontent.com/23562374/231386931-fcbe22ec-e7ee-4490-9905-0bf83cfd4470.png">

**Comment by ochaton** [comment]
WAT?

**Comment by ochaton** [comment]
@vanyarock01 released in https://github.com/moonlibs/sync/releases/tag/0.10.1
